apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: "https://github.com/bhagataws/argocd-example-apps.git"
      revision: HEAD
      files:
      - path: "guestbook/platform-chats/**/Chart.yaml"
  template:
    metadata:
      name: '{{path.basename}}-{{annotations.preferredNamespace}}'
      annotations:
        # Only update application when commits relates this chart
        argocd.argoproj.io/manifest-generate-paths: .
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: boss
      source:
        repoURL: "https://github.com/bhagataws/argocd-example-apps.git"
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        namespace: '{{annotations.preferredNamespace}}'
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
          limit: 10
        syncOptions:
        - PrunePropagationPolicy=foreground
        - ApplyOutOfSyncOnly=true
        - PruneLast=true